### ISSUE TITLE
demo

### ISSUE THREAD

**Issue by johntom** [CharlesPockert/aurelia-bs-grid#16]
Hi Charles,
I'm trying to use bs-grid but not quite sure how to implement the plugin into my skeleton-nav project. I've successfully incorporated https://github.com/PWKad/aurelia-bs-modal as a plugin and looking for similar guidelines.
Thanks,
John

**Comment by charlespockert** [comment]
Hi John, you just need to install via jspm `jspm install github:charlespockert/aurelia-bs-grid` then follow the instructions on the github readme for this repository

Are there any particular issues you are having?

I do have plans to update the readme

**Comment by charlespockert** [comment]
Hi John, FYI I've updated the readme.md so it should be a bit clearer, let me know if that helps you or if you have any more specific issues.

**Comment by johntom** [comment]
Hi,

Testing now, noticed a typo

change

jspm install github:charlespockert/aurelia-bs-modal

to

jspm install github:charlespockert/aurelia-bs-grid

Thanks,

John

**Comment by charlespockert** [comment]
Hi John, good catch, can you tell I copied most of it from the modal repo?! :)
