### ISSUE TITLE
missing img folder

### ISSUE THREAD

**Issue by johntom** [CharlesPockert/aurelia-bs-grid#18]
Hi,
I've got it working (hip hip...) but had to copy your img folder from aurelia-grid because of the folowing error:
bullet_arrow_down.png:1 GET http://localhost:9000/img/bullet_arrow_down.png 404 (Not Found)
bullet_arrow_up.png:1 GET http://localhost:9000/img/bullet_arrow_up.png 404 (Not Found)
John

**Comment by charlespockert** [comment]
I'm aware of that one - what's funny is that it was working in my demo project but I've just realised I had an img folder at the root with those exact images in it! See #8 - I'll close this and refer to the original issue as there's a potential fix on there I haven't tried

**Comment by charlespockert** [comment]
Oh and additionally - try the gitter channel too, I'm always on there: http://gitter.im/aurelia/discuss (if you aren't already there)

**Comment by johntom** [comment]
I know I've been on there and getting used to it but sometimes overwhelming so I go old school.

J
