### ISSUE TITLE
Should the grid filter row be above or below the headings?

### ISSUE THREAD

**Issue by charlespockert** [CharlesPockert/aurelia-bs-grid#38]
Or should it popup in a menu maybe?

**Comment by moshensky** [comment]
It depends. I guess it should be above, but there are cases where we need more complicated behavior, which could be configured through a dropdown menu.
One very common a little bit more complicated behavior is filtering dates from/to.

**Comment by charlespockert** [comment]
I've got an issue for customising the header row, this should take care of filtering requirements (I'll probably use this internally if I ever decide to provide some filter controls out of the box).

I'm going to see what else I might need for the app I'm writing to see if any other cases crop up
