### ISSUE TITLE
Win8 demo install issues

### ISSUE THREAD

**Issue by johntom** [CharlesPockert/aurelia-bs-grid#39]
Hi,
1) Just tried to install demo on win8 /node 0.12.6/ npm 3.1.0
2) Initially the following npm repos missing 
Error: Cannot find module 'filesize'
Error: Cannot find module 'gzip-size'
3) After installing repos I get following on gulp watch
 Error in plugin 'gulp-changed'
Message:
    EPERM, stat 'c:\Aurelia\aurelia-bs-grid-demo\dist\animation-main.js'
Details:
    errno: -4048
    code: EPERM
    path: c:\Aurelia\aurelia-bs-grid-demo\dist\animation-main.js
    fileName: c:\Aurelia\aurelia-bs-grid-demo\src\animation-main.js
[07:41:25] Plumber found unhandled error:
 SyntaxError in plugin 'gulp-babel'
Message:
    c:/Aurelia/aurelia-bs-grid-demo/src/animation-main.js: Unexpected token (6:4)

events.js:85
      throw er; // Unhandled 'error' event
            ^
Error: EPERM, stat 'c:\Aurelia\aurelia-bs-grid-demo\dist\app.html'
    at Error (native)

c:\Aurelia\aurelia-bs-grid-demo>
4) I have your plugin working within the forked skeleton annimation and with the exception of a different build process don't see what issue might be,
Thanks,
John

**Comment by charlespockert** [comment]
Hi John, I'm on the same setup - though I may have stuff that needs to go into the config etc. I'll kill my demo repo and try cloning and see if I get the same issue

**Comment by johntom** [comment]
Glad to hear it, While I have a Mac I must get everything working on windows as all my clients have win computers/servers etc. and actually prefer doing my devel on a win computer as much more experience and they are much cheaper..

J

**Comment by charlespockert** [comment]
Hi John, just checked this now and added the missing deps for npm (jspm, gzip-size and filesize).

I didn't get any of your other issues though. These are my install steps:
- Clone repo to my desktop (messy!)
- `npm install`
- `jspm install`
- `gulp watch`
- Browse to server port (9000ish) all working ok

![image](https://cloud.githubusercontent.com/assets/9073518/8777241/c4d3bf44-2eee-11e5-887c-5f47f60a7751.png)

**Comment by charlespockert** [comment]
Oh, I might add, I updated the demo to use the new release v0.0.2

**Comment by johntom** [comment]
Will test and get back

**Comment by johntom** [comment]
Works as described!
