### ISSUE TITLE
Annimation

### ISSUE THREAD

**Issue by johntom** [CharlesPockert/aurelia-bs-grid#40]
Hi,
1) In your demo I only see the annimation for the following route
http://charlespockert.github.io/aurelia-bs-grid-demo/#/mutation
2) When running locally none of routes show the annimation
John

**Comment by charlespockert** [comment]
Hi John, seems to work OK for me on Chrome and Firefox - what browser are you using?

I've not bundled the polyfills for IE so it won't work with IE yet but I'll fix that soon, though that shouldn't affect anything else

**Comment by johntom** [comment]
Chrome Version 43.0.2357.134 m

**Comment by johntom** [comment]
same results after empty cache and hard-reolad

**Comment by charlespockert** [comment]
Any messages in console? I mean to be honest the animation is only there because it was in skeleton...

Can't reproduce though on FF or Chrome. I even tried in IE on my local without bundling and it's ok

**Comment by johntom** [comment]
Nothing in console. I thought it was because I was using materialize but that does not explain what happens with your demo. Closing for now and will pick it up down the road...

**Comment by charlespockert** [comment]
Well to be honest the animation isn't anything to do with the grid so I'm
thinking you are running into some obscure bug

Let me know if you ever figure it out
