### ISSUE TITLE
Updates to support the Aurelia Framework v0.15.0

### ISSUE THREAD

**Issue by peisenmann** [CharlesPockert/aurelia-bs-grid#48]
Per today's framework updates, there are changes to how plugins are handled.

```
Unhandled promise rejection TypeError: aurelia.globalizeResources is not a function
    at a.configure (http://localhost:9010/jspm_packages/github/charlespockert/aurelia-bs-grid@0.0.2/index.js:7:13)
    at http://localhost:9010/jspm_packages/github/aurelia/framework@0.15.0/aurelia-framework.js:34:34
```

`aurelia.globalizeResources` is now `aurelia.use.globalResources`

http://aurelia.io/docs.html#the-aurelia-object

There may be additional changes necessary that could be tacked onto this issue.

**Comment by vcardins** [comment]
+1

**Comment by charlespockert** [comment]
There's some work that needs to be done - but it does mean I think I'm going to be able to remove the dependency on aurelia-compiler

The new release has the `@processContent` decorator which allows you to manually manipulate the DOM before Aurelia kicks in - this is exactly what I'm doing at the moment by using `skipContentProcessing`. 

I'd like to merge the PR then do some work to get the grid working with the new decorator - expect stuff to start moving again soon.

**Comment by peisenmann** [comment]
@CharlesPockert My intention with the pull request was to produce the minimal fix that could repair the basic run time issues experienced post-upgrade. I believe users should be able to take the `dist/index.js` that was just merged in and paste it over top of their local `jspm_packages/github/charlespockert/aurelia-bs-grid@0.0.2/index.js` if you're not ready to kick out a new tag.

Also, I kicked up the version in your `package.json` to 0.0.3.
