### ISSUE TITLE
Demo

### ISSUE THREAD

**Issue by johntom** [CharlesPockert/aurelia-bs-grid#54]
Hi Charles,
I decided to try the grid with materialize as I have a note to wait for version .3x. At any rate when I test the demo I get the following

```
Unhandled promise rejection TypeError: Cannot read property 'use' of undefined
    at y.configure (http://localhost:9000/jspm_packages/github/charlespockert/aurelia-bs-grid@master/index.js:7:28)
    at http://localhost:9000/jspm_packages/github/aurelia/framework@0.14.0/aurelia-framework.js:25:34
    at run (http://localhost:9000/jspm_packages/npm/core-js@0.9.18/modules/es6.promise.js:91:43)
    at http://localhost:9000/jspm_packages/npm/core-js@0.9.18/modules/es6.promise.js:105:11
    at module.exports (http://localhost:9000/jspm_packages/npm/core-js@0.9.18/modules/$.invoke.js:6:25)
    at queue.(anonymous function) (http://localhost:9000/jspm_packages/npm/core-js@0.9.18/modules/$.task.js:40:9)
    at Number.run (http://localhost:9000/jspm_packages/npm/core-js@0.9.18/modules/$.task.js:27:7)
    at listner (http://localhost:9000/jspm_packages/npm/core-js@0.9.18/modules/$.task.js:31:9)(anonymous function) @ :9000/jspm_packages/npm/core-js@0.9.18/modules/es6.promise.js:139
```

Thanks
John

**Comment by charlespockert** [comment]
Hi John, yeah I'm aware of this, there was a PR I merged to make it work with the new version of Aurelia but it turns out Rob did some work to get rid of one of the classes the compiler uses and therefore the DI just complains now. I'm going to move the codebase to TypeScript and use the new `@processContent` decorator when I get the chance. 

Just got a lot of projects on a the moment :( will get round to it as soon as I can!

**Comment by johntom** [comment]
No worries, just curious about the possible use of materializecss. Would also like to know if you have  select as a filter? I did see a previous ticket on this subject after Ii submitted. Have a nice weekend.

John

**Comment by charlespockert** [comment]
Should be fixed now @johntom - just had to test to be sure, I'll close this issue unless you say otherwise :)

**Comment by johntom** [comment]
Hi,
I just re-installed the repo but get the following when loading in browser. No errors reported from gulp watch...
John

(index):23 GET http://localhost:9000/dist/app-bundle.html 404 (Not Found)
es6-module-loader.js:7 GET http://localhost:9000/dist/app-bundle.js 404 (Not Found)f @ es6-module-loader.js:7$__Object$defineProperty.value @ es6-module-loader.js:7c @ es6-module-loader.js:7b @ es6-module-loader.js:7$__Object$defineProperty.value @ es6-module-loader.js:7$__global.upgradeSystemLoader.e.fetch @ system.js:1$__global.upgradeSystemLoader.e.fetch @ system.js:1$__global.upgradeSystemLoader.e.fetch @ system.js:1(anonymous function) @ es6-module-loader.js:7O @ es6-module-loader.js:7K @ es6-module-loader.js:7h.7.y.when @ es6-module-loader.js:7h.7.v.run @ es6-module-loader.js:7h.3.a._drain @ es6-module-loader.js:7h.3.a.drain @ es6-module-loader.js:7b @ es6-module-loader.js:7
es6-module-loader.js:7 Potentially unhandled rejection [5] Error loading "github:aurelia/bootstrapper@0.16.0" at http://localhost:9000/jspm_packages/github/aurelia/bootstrapper@0.16.0.js
Error loading "app-bundle" at http://localhost:9000/dist/app-bundle.js
Not Found: http://localhost:9000/dist/app-bundle.js (WARNING: non-Error used)(anonymous function) @ es6-module-loader.js:7f @ es6-module-loader.js:7i @ es6-module-loader.js:7
browser-sync-client.1.9.2.js:2 GET http://localhost:9000/browser-sync/socket.io/?EIO=3&transport=polling&t=1441325362160-4 net::ERR_CONNECTION_REFUSEDu.16.Request.create @ browser-sync-client.1.9.2.js:2Request @ browser-sync-client.1.9.2.js:2u.16.XHR.request @ browser-sync-client.1.9.2.js:2u.16.XHR.doPoll @ browser-sync-client.1.9.2.js:2u.17.Polling.poll @ browser-sync-client.1.9.2.js:2u.17.Polling.doOpen @ browser-sync-client.1.9.2.js:2u.13.Transport.open @ browser-sync-client.1.9.2.js:1u.12.Socket.open @ browser-sync-client.1.9.2.js:1Socket @ browser-sync-client.1.9.2.js:1Socket @ browser-sync-client.1.9.2.js:1u.3.Manager.open.Manager.connect @ browser-sync-client.1.9.2.js:1(anonymous function) @ browser-sync-client.1.9.2.js:1
browser-sync-client.1.9.2.js:2 GET http://localhost:9000/browser-sync/socket.io/?EIO=3&transport=polling&t=1441325366166-5 net::ERR_CONNECTION_REFUSEDu.16.Request.create @ browser-sync-client.1.9.2.js:2Request @ browser-sync-client.1.9.2.js:2u.16.XHR.request @ browser-sync-client.1.9.2.js:2u.16.XHR.doPoll @ browser-sync-client.1.9.2.js:2u.17.Polling.poll @ browser-sync-client.1.9.2.js:2u.17.Polling.doOpen @ browser-sync-client.1.9.2.js:2u.13.Transport.open @ browser-sync-client.1.9.2.js:1u.12.Socket.open @ browser-sync-client.1.9.2.js:1Socket @ browser-sync-client.1.9.2.js:1Socket @ browser-sync-client.1.9.2.js:1u.3.Manager.open.Manager.connect @ browser-sync-client.1.9.2.js:1(anonymous function) @ browser-sync-client.1.9.2.js:1
browser-sync-client.1.9.2.js:2 GET http://localhost:9000/browser-sync/socket.io/?EIO=3&transport=polling&t=1441325371172-6 net::ERR_CONNECTION_REFUSEDu.16.Request.create @ browser-sync-client.1.9.2.js:2Request @ browser-sync-client.1.9.2.js:2u.16.XHR.request @ browser-sync-client.1.9.2.js:2u.16.XHR.doPoll @ browser-sync-client.1.9.2.js:2u.17.Polling.poll @ browser-sync-client.1.9.2.js:2u.17.Polling.doOpen @ browser-sync-client.1.9.2.js:2u.13.Transport.open @ browser-sync-client.1.9.2.js:1u.12.Socket.open @ browser-sync-client.1.9.2.js:1Socket @ browser-sync-client.1.9.2.js:1Socket @ browser-sync-client.1.9.2.js:1u.3.Manager.open.Manager.connect @ browser-sync-client.1.9.2.js:1(anonymous function) @ browser-sync-client.1.9.2.js:1
