### ISSUE TITLE
demo

### ISSUE THREAD

**Issue by johntom** [CharlesPockert/aurelia-bs-grid#55]
Hi,
As per blog 

```
http://blog.durandal.io/2015/09/05/aurelia-early-september-release-notes/

```

 i just ran

```
jspm install aurelia-animator-css aurelia-binding aurelia-bootstrapper aurelia-dependency-injection aurelia-framework aurelia-http-client aurelia-router aurelia-event-aggregator aurelia-history-browser aurelia-loader-default aurelia-loader aurelia-metadata aurelia-route-recognizer aurelia-templating-binding aurelia-templating-resources aurelia-templating-router aurelia-templating aurelia-logging aurelia-task-queue aurelia-history aurelia-path
```

and still get error but get the following when loading in browser. No errors reported from gulp watch...
John
(index):23 GET http://localhost:9000/dist/app-bundle.html 404 (Not Found)
es6-module-loader.js:7 GET http://localhost:9000/dist/app-bundle.js 404 (Not Found)f @ es6-module-loader.js:7$__Object$defineProperty.value @ es6-module-loader.js:7c @ es6-module-loader.js:7b @ es6-module-loader.js:7$__Object$defineProperty.value @ es6-module-loader.js:7$__global.upgradeSystemLoader.e.fetch @ system.js:1$__global.upgradeSystemLoader.e.fetch @ system.js:1$__global.upgradeSystemLoader.e.fetch @ system.js:1(anonymous function) @ es6-module-loader.js:7O @ es6-module-loader.js:7K @ es6-module-loader.js:7h.7.y.when @ es6-module-loader.js:7h.7.v.run @ es6-module-loader.js:7h.3.a._drain @ es6-module-loader.js:7h.3.a.drain @ es6-module-loader.js:7b @ es6-module-loader.js:7
es6-module-loader.js:7 Potentially unhandled rejection [5] Error loading "npm:core-js@0.9.18" at http://localhost:9000/jspm_packages/npm/core-js@0.9.18.js
Error loading "npm:core-js@0.9.18" from "github:aurelia/bootstrapper@0.17.0" at http://localhost:9000/jspm_packages/github/aurelia/bootstrapper@0.17.0.js
Error loading "app-bundle" at http://localhost:9000/dist/app-bundle.js
Not Found: http://localhost:9000/dist/app-bundle.js (WARNING: non-Error used)(anonymous function) @ es6-module-loader.js:7f @ es6-module-loader.js:7i @ es6-module-loader.js:7
es6-module-loader.js:7 GET http://localhost:9000/dist/app-bundle.js 404 (Not Found)f @ es6-module-loader.js:7$__Object$defineProperty.value @ es6-module-loader.js:7c @ es6-module-loader.js:7b @ es6-module-loader.js:7$__Object$defineProperty.value @ es6-module-loader.js:7$__global.upgradeSystemLoader.e.fetch @ system.js:1$__global.upgradeSystemLoader.e.fetch @ system.js:1$__global.upgradeSystemLoader.e.fetch @ system.js:1(anonymous function) @ es6-module-loader.js:7O @ es6-module-loader.js:7K @ es6-module-loader.js:7h.7.y.when @ es6-module-loader.js:7h.7.v.run @ es6-module-loader.js:7h.3.a._drain @ es6-module-loader.js:7h.3.a.drain @ es6-module-loader.js:7b @ es6-module-loader.js:7

**Comment by charlespockert** [comment]
Hi John, try running jspm unbundle first, I may have left the config
bundled when I committed

**Comment by johntom** [comment]
Hey Charles
After last suggestion I get.

```
Unhandled promise rejection TypeError: Error loading "github:charlespockert/aurelia-bs-grid@master/grid/grid.html!template-registry-entry" at http://localhost:9000/jspm_packages/github/charlespockert/aurelia-bs-grid@master/grid/grid.html(…)
```

**Comment by charlespockert** [comment]
Ok I'll have a look - I should really get this one working (it was more intended to just update the demo site) but since people are using it to tinker with I think it would be useful to make it actually work after cloning!

**Comment by johntom** [comment]
No worries and no rush, I just like to see the progess you've been making as I love using grids.

**Comment by charlespockert** [comment]
Big updates soon!

**Comment by charlespockert** [comment]
@johntom Should be ok now - published an interim release

You may need to `jspm install css=github:systemjs/plugin-css` - this gives plugin-css the `css` alias in packages (it seems to want this by default as it uses the file extension to resolve the plugin module name) 

I needed to perform the above to get css imports working with skeleton-navigation

**Comment by johntom** [comment]
Hi.
I tried a few things as I still can't get it to work.  I got skel-nav to work without jspm install css=github:systemjs/plugin-css
Thanks,
John

Made sure jspm was up to date 0.16.9.
jspm unbundle
gulp bundle
jspm install css=github:systemjs/plugin-css

get the followin in browser console with no erorrs from cmd prompt.

GET http://localhost:9000/dist/app-bundle.html 404 (Not Found)
aurelia-logging-console.js:38 DEBUG [aurelia] Loading plugin github:aurelia/templating-binding@0.14.0.
aurelia-logging-console.js:38 DEBUG [aurelia] Configured plugin github:aurelia/templating-binding@0.14.0.
aurelia-logging-console.js:38 DEBUG [aurelia] Loading plugin github:aurelia/templating-resources@0.14.0.
aurelia-logging-console.js:38 DEBUG [aurelia] Configured plugin github:aurelia/templating-resources@0.14.0.
aurelia-logging-console.js:38 DEBUG [aurelia] Loading plugin github:aurelia/history-browser@0.7.0.
aurelia-logging-console.js:38 DEBUG [aurelia] Configured plugin github:aurelia/history-browser@0.7.0.
aurelia-logging-console.js:38 DEBUG [aurelia] Loading plugin github:aurelia/templating-router@0.15.0.
aurelia-logging-console.js:38 DEBUG [aurelia] Configured plugin github:aurelia/templating-router@0.15.0.
aurelia-logging-console.js:38 DEBUG [aurelia] Loading plugin github:aurelia/event-aggregator@0.7.0.
aurelia-logging-console.js:38 DEBUG [aurelia] Configured plugin github:aurelia/event-aggregator@0.7.0.
aurelia-logging-console.js:38 DEBUG [aurelia] Loading plugin aurelia-animator-css.
aurelia-logging-console.js:38 DEBUG [aurelia] Configured plugin aurelia-animator-css.
aurelia-logging-console.js:38 DEBUG [aurelia] Loading plugin charlespockert/aurelia-bs-grid.
aurelia-logging-console.js:38 DEBUG [aurelia] Configured plugin charlespockert/aurelia-bs-grid.
es6-module-loader.js:7 GET http://localhost:9000/jspm_packages/github/CharlesPockert/aurelia-compiler@0.0.7.js 404 (Not Found)f @ es6-module-loader.js:7$__Object$defineProperty.value @ es6-module-loader.js:7c @ es6-module-loader.js:7b @ es6-module-loader.js:7$__Object$defineProperty.value @ es6-module-loader.js:7$__global.upgradeSystemLoader.e.fetch @ system.js:1$__global.upgradeSystemLoader.e.fetch @ system.js:1$__global.upgradeSystemLoader.e.fetch @ system.js:1(anonymous function) @ es6-module-loader.js:7O @ es6-module-loader.js:7K @ es6-module-loader.js:7h.7.y.when @ es6-module-loader.js:7h.7.v.run @ es6-module-loader.js:7h.3.a._drain @ es6-module-loader.js:7h.3.a.drain @ es6-module-loader.js:7b @ es6-module-loader.js:7
3es6.promise.js:139 Unhandled promise rejection Error loading "github:CharlesPockert/aurelia-compiler@0.0.7" at http://localhost:9000/jspm_packages/github/CharlesPockert/aurelia-compiler@0.0.7.js
Error loading "github:CharlesPockert/aurelia-compiler@0.0.7" from "github:charlespockert/aurelia-bs-grid@master/grid/grid" at http://localhost:9000/jspm_packages/github/charlespockert/aurelia-bs-grid@master/grid/grid.js
Not Found: http://localhost:9000/jspm_packages/github/CharlesPockert/aurelia-compiler@0.0.7.js(anonymous function) @ es6.promise.js:139module.exports @ $.invoke.js:6queue.(anonymous function) @ $.task.js:40run @ $.task.js:27listner @ $.task.js:31

**Comment by charlespockert** [comment]
Hi @johntom sorry but I reckon this is due case-sensitivity

Did you install using `jspm install github:CharlesPockert\aurelia-bs-grid` or lowercase `jspm install github:charlespockert/aurelia-bs-grid`?

I really need to change my username to lowercase on github - I didn't realise it would cause this many issues

**Comment by charlespockert** [comment]
@johntom ok - I've gone through the pain of a mixed case username and decided to change it to lower case. Hopefully this has fixed all the issues (the repos have been updated and a re-release of v0.0.3 has been done)

**Comment by charlespockert** [comment]
I've updated to v0.0.4 to ensure you don't have any cache issues

**Comment by johntom** [comment]
now I seem to remember that case-sensitivity issue. Will try this afternoon and get back to you. Thanks for all your support.

**Comment by johntom** [comment]
Hi,
Still can't get it to work and I'm on a win10 and not for a lack of trying.
Also followed issues/55 and then did a
gulp unbundle
and then gulp bundle which complained about the bundle file so I changed it to.

```
  gulp.task('bundle', function (done) {
            var distFile = 'aurelia.js';
            jspm.bundle(
              [
                'aurelia-bootstrapper',
                'aurelia-http-client',
                'aurelia-dependency-injection',
                'aurelia-framework',
                'aurelia-router',
                'github:aurelia/animator-css@0.15.0',
                'github:aurelia/templating@0.15.3',
                'github:aurelia/history@0.7.0',
                'github:aurelia/history-browser@0.8.0',
                'github:aurelia/templating-router@0.16.1',
                'github:aurelia/templating-resources@0.15.2',
                'github:aurelia/templating-binding@0.15.0',
                'github:aurelia/binding@0.9.1',
                'github:aurelia/loader-default@0.10.0',
                'github:aurelia/logging-console@0.6.2',

              ].join(' + '),
              distFile,
              {inject:true,minify:false}
            ).then(function(){
```

gulp watch
but still get errors.

localhost/:23 GET http://localhost:9000/dist/app-bundle.html 404 (Not Found)
es6-module-loader.js:7 GET http://localhost:9000/dist/aurelia.js 404 (Not Found)f @ es6-module-loader.js:7$__Object$defineProperty.value @ es6-module-loader.js:7c @ es6-module-loader.js:7b @ es6-module-loader.js:7$__Object$defineProperty.value @ es6-module-loader.js:7$__global.upgradeSystemLoader.e.fetch @ system.js:1$__global.upgradeSystemLoader.e.fetch @ system.js:1$__global.upgradeSystemLoader.e.fetch @ system.js:1(anonymous function) @ es6-module-loader.js:7O @ es6-module-loader.js:7K @ es6-module-loader.js:7h.7.y.when @ es6-module-loader.js:7h.7.v.run @ es6-module-loader.js:7h.3.a._drain @ es6-module-loader.js:7h.3.a.drain @ es6-module-loader.js:7b @ es6-module-loader.js:7
es6-module-loader.js:7 Potentially unhandled rejection [5] Error loading "github:aurelia/bootstrapper@0.16.0" at http://localhost:9000/jspm_packages/github/aurelia/bootstrapper@0.16.0.js
Error loading "aurelia" at http://localhost:9000/dist/aurelia.js
Not Found: http://localhost:9000/dist/aurelia.js (WARNING: non-Error used)(anonymous function) @ es6-module-loader.js:7f @ es6-module-loader.js:7i @ es6-module-loader.js:7

**Comment by charlespockert** [comment]
Hi @johntom I believe this is more of a bundling issue and out of scope for the grid itself - any chance you can move the line of query to the gitter chan instead?

I'm going to close this issue as I believe the problems with the repo are fixed (other users have reported it working and I've checked it a few times myself and it appears to be ok)
