### ISSUE TITLE
your github references are incorrect

### ISSUE THREAD

**Issue by jadrake75** [CharlesPockert/aurelia-bs-grid#56]
in your various configs you refer to your module as

http://github.com/charlespockert/aurelia-bs-grid

but, it should be

http://github.com/CharlesPockert/aurelia-bs-grid

depending on your OS and how you run the project it systemjs is not able to find resources.

**Comment by charlespockert** [comment]
thanks for this - never considered the case sensitivity (would have lowercased my username had I thought it would cause an issue!)

**Comment by jadrake75** [comment]
No problems.  I seem to have issues on windows 10, but not 7.  But it sent
off warning signals right away when I saw your capitalized user name,
portal.

**Comment by charlespockert** [comment]
Yeah I'm a bit annoyed to be honest - I'd rather have it lowercase, it's just another thing to go wrong, might contact staff if I can't find a way to change it since you can't have two usernames the same...

**Comment by charlespockert** [comment]
@jadrake75 fixed this: https://github.com/CharlesPockert/aurelia-bs-grid/releases/tag/0.0.3
