### ISSUE TITLE
Always downloading v 0.0.2 on installing

### ISSUE THREAD

**Issue by vcardins** [CharlesPockert/aurelia-bs-grid#58]
For some reason I can't install the latest version 0.0.3, it always get 0.0.2

```
jspm install github:charlespockert/aurelia-bs-grid
Looking up github:charlespockert/aurelia-bs-grid
Creating registry cache...
Downloading github:charlespockert/aurelia-bs-grid@0.0.2*
Looking up github:twbs/bootstrap
Looking up github:gooy/aurelia-compiler
 Downloading github:gooy/aurelia-compiler@0.0.5
...
```

**Comment by charlespockert** [comment]
Hi @vcardins, I'm actually working on getting this up and running with the latest Aurelia as we speak so sit tight!

**Comment by vcardins** [comment]
Thanks

**Comment by charlespockert** [comment]
@vcardins try `jspm install <reponame>@<branchorreleasename>`

E.g. @0.0.3 or @master

I updated master with a demo app so it's all in one repo so you should be able to clone and run gulp watch to view the demo

**Comment by charlespockert** [comment]
Actually no it won't work yet, I think I was conflict merging before I left and didn't get round to checking in :-1: should be done by tonight though (in about 5/6 hours from now)

**Comment by vcardins** [comment]
You're right, just checked again: http://screencast.com/t/1uGHl9TuqHp6.
Thanks for your cooperation, anyway !!

**Comment by charlespockert** [comment]
@vcardins FYI this should be working now if you want to install the release version, please let me know if you have any issues
