### ISSUE TITLE
Is is possible that this repo is not up to date with latest aurelia framework.

### ISSUE THREAD

**Issue by paulvanbladel** [CharlesPockert/aurelia-bs-grid#59]
Looks great !
V0.0.2 still uses aurelia.globalizeResources.
Master seems to be more aligned with latest aurelia framework.

**Comment by charlespockert** [comment]
@paulvanbladel Fixed: https://github.com/CharlesPockert/aurelia-bs-grid/releases/tag/0.0.3 - let me know if issues

**Comment by charlespockert** [comment]
@paulvanbladel FYI there's an update to v0.0.4 if you are interested, there were some github mixed case username issues so I decided to switch my username and fix the references in the repos.

No functional changes yet though  :watch:

**Comment by paulvanbladel** [comment]
Cool.  Thanks a lot for the info.
