### ISSUE TITLE
New install error

### ISSUE THREAD

**Issue by eaidland** [CharlesPockert/aurelia-bs-grid#61]
Ran the  "jspm install github:charlespockert/aurelia-bs-grid"

```
jspm install github:charlespockert/aurelia-bs-grid
     Looking up github:charlespockert/aurelia-bs-grid
     Updating registry cache...
     Looking up github:aurelia/bootstrapper
     Looking up github:aurelia/binding
     Looking up github:aurelia/metadata
     Looking up github:aurelia/dependency-injection
     Looking up github:CharlesPockert/aurelia-compiler
     Looking up github:aurelia/logging
     Looking up github:aurelia/templating
     Looking up npm:core-js
     Looking up github:aurelia/templating-router
     Looking up github:aurelia/loader-default
     Looking up github:aurelia/event-aggregator
     Looking up github:aurelia/framework
     Looking up github:aurelia/templating-resources
     Looking up github:aurelia/history
     Looking up github:aurelia/history-browser
     Looking up github:aurelia/templating-binding
     Looking up github:aurelia/router
     Looking up github:aurelia/logging-console
     Looking up github:aurelia/task-queue
     Looking up github:aurelia/html-template-element
     Looking up github:systemjs/plugin-json
     Looking up github:jspm/nodelibs-process
     Looking up github:aurelia/loader
     Looking up github:jspm/nodelibs-fs
     Looking up github:aurelia/path
     Looking up npm:process
     Looking up github:zloirock/core-js
     Looking up github:aurelia/route-recognizer
ok   Installed github:CharlesPockert/aurelia-compiler@^0.0.7 (0.0.7)
ok   Installed charlespockert/aurelia-bs-grid as github:charlespockert/aurelia-bs-grid@^0.0.3 (0.0.3)
     Removing package files for github:charlespockert/aurelia-compiler@0.0.7
     Installed Forks

                  github:aurelia/fetch-client 0.1.1 0.2.0

     To inspect individual package constraints, use jspm inspect registry:name.


warn core-js@0.9.18 is out of date. Use jspm dl-loader to update.

ok   Install complete.
```

And then I add the plugin:

```
.plugin('charlespockert/aurelia-bs-grid')
```

When I load up my page chrome console log:

```
DEBUG [aurelia] Configured plugin aurelia-auth.
system.src.js:3987 GET http://localhost:9000/jspm_packages/github/CharlesPockert/aurelia-compiler@0.0.7.js 404 (Not Found)M @ system.src.js:3987o.fetch @ system.src.js:3987Promise @ es6.promise.js:193o.fetch @ system.src.js:3987g @ system.src.js:3987(anonymous function) @ system.src.js:3987a @ system.src.js:3987a @ system.src.js:3987n @ system.src.js:3987(anonymous function) @ system.src.js:3987(anonymous function) @ system.src.js:3987(anonymous function) @ system.src.js:3987run @ es6.promise.js:91(anonymous function) @ es6.promise.js:105module.exports @ $.invoke.js:6queue.(anonymous function) @ $.task.js:40run @ $.task.js:27listner @ $.task.js:31
system.src.js:3987 GET http://localhost:9000/dist/css.js 404 (Not Found)M @ system.src.js:3987o.fetch @ system.src.js:3987Promise @ es6.promise.js:193o.fetch @ system.src.js:3987g @ system.src.js:3987(anonymous function) @ system.src.js:3987a @ system.src.js:3987a @ system.src.js:3987n @ system.src.js:3987(anonymous function) @ system.src.js:3987(anonymous function) @ system.src.js:3987(anonymous function) @ system.src.js:3987run @ es6.promise.js:91(anonymous function) @ es6.promise.js:105module.exports @ $.invoke.js:6queue.(anonymous function) @ $.task.js:40run @ $.task.js:27listner @ $.task.js:31
es6.promise.js:139 Unhandled promise rejection Error: XHR error (404 Not Found) loading http://localhost:9000/jspm_packages/github/CharlesPockert/aurelia-compiler@0.0.7.js
    Error loading http://localhost:9000/jspm_packages/github/CharlesPockert/aurelia-compiler@0.0.7.js as "CharlesPockert/aurelia-compiler" from http://localhost:9000/jspm_packages/github/charlespockert/aurelia-bs-grid@0.0.3/grid/grid.js
    at r (http://localhost:9000/jspm_packages/system.js:4:10674)
    at XMLHttpRequest.o.onreadystatechange (http://localhost:9000/jspm_packages/system.js:4:11199)(anonymous function) @ es6.promise.js:139module.exports @ $.invoke.js:6queue.(anonymous function) @ $.task.js:40run @ $.task.js:27listner @ $.task.js:31
es6.promise.js:139 Unhandled promise rejection Error: XHR error (404 Not Found) loading http://localhost:9000/jspm_packages/github/CharlesPockert/aurelia-compiler@0.0.7.js
    Error loading http://localhost:9000/jspm_packages/github/CharlesPockert/aurelia-compiler@0.0.7.js as "CharlesPockert/aurelia-compiler" from http://localhost:9000/jspm_packages/github/charlespockert/aurelia-bs-grid@0.0.3/grid/grid.js
    at r (http://localhost:9000/jspm_packages/system.js:4:10674)
    at XMLHttpRequest.o.onreadystatechange (http://localhost:9000/jspm_packages/system.js:4:11199)(anonymous function) @ es6.promise.js:139module.exports @ $.invoke.js:6queue.(anonymous function) @ $.task.js:40run @ $.task.js:27listner @ $.task.js:31
es6.promise.js:139 Unhandled promise rejection Error: XHR error (404 Not Found) loading http://localhost:9000/jspm_packages/github/CharlesPockert/aurelia-compiler@0.0.7.js
    Error loading http://localhost:9000/jspm_packages/github/CharlesPockert/aurelia-compiler@0.0.7.js as "CharlesPockert/aurelia-compiler" from http://localhost:9000/jspm_packages/github/charlespockert/aurelia-bs-grid@0.0.3/grid/grid.js
    at r (http://localhost:9000/jspm_packages/system.js:4:10674)
    at XMLHttpRequest.o.onreadystatechange (http://localhost:9000/jspm_packages/system.js:4:11199
```

Why is it looking for the compiler when it says in the install that it has been removed?
Removing package files for github:charlespockert/aurelia-compiler@0.0.7

config.js:

```
"charlespockert/aurelia-bs-grid": "github:charlespockert/aurelia-bs-grid@0.0.3",
    "github:CharlesPockert/aurelia-compiler@0.0.7": {
      "aurelia-loader": "github:aurelia/loader@0.9.0",
      "aurelia-loader-default": "github:aurelia/loader-default@0.10.0",
      "aurelia-templating": "github:aurelia/templating@0.15.3"
    },
    "github:charlespockert/aurelia-bs-grid@0.0.3": {
      "CharlesPockert/aurelia-compiler": "github:CharlesPockert/aurelia-compiler@0.0.7",
      "aurelia-binding": "github:aurelia/binding@0.9.1",
      "aurelia-bootstrapper": "github:aurelia/bootstrapper@0.17.0",
      "aurelia-dependency-injection": "github:aurelia/dependency-injection@0.10.1",
      "aurelia-logging": "github:aurelia/logging@0.7.0",
      "aurelia-metadata": "github:aurelia/metadata@0.8.0",
      "aurelia-templating": "github:aurelia/templating@0.15.3"
    },
```

package.json:

```
"charlespockert/aurelia-bs-grid": "github:charlespockert/aurelia-bs-grid@^0.0.3",
```

![image](https://cloud.githubusercontent.com/assets/10772259/10067565/f69e8e5e-629d-11e5-9a6a-d9a58eaec2ba.png)

**Comment by charlespockert** [comment]
@eaidland

Got someone else with this issue - not really sure what's going on but I suspect it's something to do with my upper/lower case user name on github - can you please try installing with case sensitivity in mind:

`jspm install github:CharlesPockert\aurelia-bs-grid` and see if you get any difference...

I bet that because it's installed the grid in the lower case directory, that it can't find the compiler plugin in the proper cased directory...

I really need to find out how to change my github username to lower case

You might want to uninstall it first to make sure the directory has been removed

**Comment by charlespockert** [comment]
I'm changing my username to lowercase, bear with me!

**Comment by eaidland** [comment]
Thanks! Just let me/us know when It's ready :+1:

**Comment by charlespockert** [comment]
@eaidland ok, I think that should do it - hopefully it's not broken, I really don't have time to test at the moment sorry :( 

Any chance you have a go for me?

I have a nice shiny new lowercase username! Lesson learnt!

**Comment by eaidland** [comment]
Sure! Installed it again. Got this message. Something I've missed mayby?
![image](https://cloud.githubusercontent.com/assets/10772259/10071196/272a73ca-62b8-11e5-920b-a05447abee18.png)

**Comment by charlespockert** [comment]
Looks like it's still looking for the uppercase variant - can you uninstall it and the compiler repo and try installing using lowercase `jspm install github:charlespockert/aurelia-bs-grid`

**Comment by eaidland** [comment]
I uninstalled everything:

```
jspm uninstall github:charlespockert/aurelia-bs-grid

warn Dependency github:charlespockert/aurelia-bs-grid is not an existing primary install.

ok   Uninstall complete.
```

Saw the refs in config and package wasn't removed. So I did it manually. That also goes for the folder. 

Ran the  `jspm install github:charlespockert/aurelia-bs-grid`
New folder with content. 
![image](https://cloud.githubusercontent.com/assets/10772259/10071356/897defd8-62b9-11e5-8aaf-fe5767195ecf.png)

config:

```
"charlespockert/aurelia-bs-grid": "github:charlespockert/aurelia-bs-grid@0.0.3",
 "github:charlespockert/aurelia-bs-grid@0.0.3": {
      "aurelia-binding": "github:aurelia/binding@0.9.1",
      "aurelia-bootstrapper": "github:aurelia/bootstrapper@0.17.0",
      "aurelia-dependency-injection": "github:aurelia/dependency-injection@0.10.1",
      "aurelia-logging": "github:aurelia/logging@0.7.0",
      "aurelia-metadata": "github:aurelia/metadata@0.8.0",
      "aurelia-templating": "github:aurelia/templating@0.15.3",
      "charlespockert/aurelia-compiler": "github:charlespockert/aurelia-compiler@0.0.7"
    },
    "github:charlespockert/aurelia-compiler@0.0.7": {
      "aurelia-loader": "github:aurelia/loader@0.9.0",
      "aurelia-loader-default": "github:aurelia/loader-default@0.10.0",
      "aurelia-templating": "github:aurelia/templating@0.15.3"
    },
```

and package

```
"charlespockert/aurelia-bs-grid": "github:charlespockert/aurelia-bs-grid@^0.0.3",
```

gulp build then watch.
![image](https://cloud.githubusercontent.com/assets/10772259/10071394/d18ba54a-62b9-11e5-9eb3-1b40c8c9ce3d.png)

So where the uppercase comes from I've got no idea

**Comment by eaidland** [comment]
Ah.... 
![image](https://cloud.githubusercontent.com/assets/10772259/10071440/28339a1a-62ba-11e5-9562-85a280bef3e8.png)

![image](https://cloud.githubusercontent.com/assets/10772259/10071499/97b7819e-62ba-11e5-8d82-77e1e4cae2c5.png)

**Comment by charlespockert** [comment]
aha! nice spot! Fixing...

**Comment by charlespockert** [comment]
@eaidland Right, sorry for all the messing about, lowercase usernames from now on and forever!! I've re-released as v0.0.3

**Comment by eaidland** [comment]
@charlespockert Np! Just glad that you update :+1: 
Uninstalled, reinstalled... Saw there were still old refs in the dist folder
![image](https://cloud.githubusercontent.com/assets/10772259/10072116/5de38b5c-62bf-11e5-8931-b5374f007557.png)

Which writes uppercase in the grid.js
![image](https://cloud.githubusercontent.com/assets/10772259/10072136/730e5fe8-62bf-11e5-8a8b-76b6c5d9096d.png)

**Comment by charlespockert** [comment]
Damn, didn't build it just edited the files!

**Comment by charlespockert** [comment]
@eaidland Ok, _this_ time... re-released again. Absolute nghtmare, thanks for your patience - I'm not sure why github even allows you to install a mixed case repo using the wrong case....!

**Comment by eaidland** [comment]
Hehe no worries. Will reinstall and test :+1:

**Comment by eaidland** [comment]
Strange.... Don't see any refs with uppercase...
![image](https://cloud.githubusercontent.com/assets/10772259/10072370/5af6ff62-62c1-11e5-90c5-4bd3ca8d6583.png)

config:

```
"charlespockert/aurelia-bs-grid": "github:charlespockert/aurelia-bs-grid@0.0.3",
  "github:charlespockert/aurelia-bs-grid@0.0.3": {
      "aurelia-binding": "github:aurelia/binding@0.9.1",
      "aurelia-bootstrapper": "github:aurelia/bootstrapper@0.17.0",
      "aurelia-dependency-injection": "github:aurelia/dependency-injection@0.10.1",
      "aurelia-logging": "github:aurelia/logging@0.7.0",
      "aurelia-metadata": "github:aurelia/metadata@0.8.0",
      "aurelia-templating": "github:aurelia/templating@0.15.3",
      "charlespockert/aurelia-compiler": "github:charlespockert/aurelia-compiler@0.0.7"
    },
    "github:charlespockert/aurelia-compiler@0.0.7": {
      "aurelia-loader": "github:aurelia/loader@0.9.0",
      "aurelia-loader-default": "github:aurelia/loader-default@0.10.0",
      "aurelia-templating": "github:aurelia/templating@0.15.3"
    },
```

**Comment by charlespockert** [comment]
**Head explodes**

Ok going to sync with my local and do a search in the src....

**Comment by eaidland** [comment]
Hehe. I'll have a look and see if there are any refs in code. At the moment I've only found functions, which shouldn't matter...

![image](https://cloud.githubusercontent.com/assets/10772259/10072432/e6ded5d6-62c1-11e5-8ddc-959b490f9516.png)

**Comment by charlespockert** [comment]
There's one in the compiler repo: that might be it:

```
Sytem.register(["github:CharlesPockert/aurelia-compiler@0.0.7/index"], function($__export) {
    2    return {  setters: [function(m) { for (var p in m) $__export(p, m[p]); }],  execute: function() {}  };
    3  });
```

**Comment by eaidland** [comment]
Lets have another go :+1:

**Comment by charlespockert** [comment]
Going to do a fresh install on skeleton and see how I get on - this worked on my machine though, what OS are you running?

**Comment by eaidland** [comment]
Win 10

**Comment by charlespockert** [comment]
8.1 here, maybe worked because I installed with the right case - checking now

**Comment by charlespockert** [comment]
@eaidland ok - sorted, try deleting the whole `jspm_packages/github/charlespockert` folder and make sure you clean your config.js of all traces of my name and then try the reinstall

It's weird, jspm lets you install with the wrong case but won't let you uninstall with the wrong case and the config.js gets into a mess..

**Comment by eaidland** [comment]
Now I wondering if there's some cache thing going on. Can't understand why the old refs are there..

![image](https://cloud.githubusercontent.com/assets/10772259/10072688/d43d19a4-62c3-11e5-9374-82aec410e692.png)

**Comment by charlespockert** [comment]
Maybe I missed a build folder - are you using AMD format or something else?

**Comment by eaidland** [comment]
?

System.config({
  defaultJSExtensions: true,
  transpiler: "babel",
  babelOptions: {
    "optional": [
      "es7.decorators",
      "es7.classProperties",
      "runtime"
    ]
  },

**Comment by charlespockert** [comment]
@eaidland Ah yeah, it looks like it might be that JSPM caches your files for a version (to save having to download them again) so you are just getting the incorrect build files again and again

https://github.com/jspm/registry/issues/295#issuecomment-86203103

I've released v0.0.4 - hopefully because it's a new release it won't be in your cache, give it a try

**Comment by charlespockert** [comment]
You can kill the cache here on windows: `C:\Users\<username>\AppData\Local\.jspm\packages\github\`

**Comment by eaidland** [comment]
jspm  cache-clear
removed folder, config refs and package refs
jspm install github:charlespockert/aurelia-bs-grid
Saw the new 0.4 was added
gulp build then watch.

![image](https://cloud.githubusercontent.com/assets/10772259/10072888/495b43b8-62c5-11e5-8eeb-4fad78557cf5.png)

Maybe I need to add the css ref?
![image](https://cloud.githubusercontent.com/assets/10772259/10072944/8e39a0ba-62c5-11e5-81ed-20c96a3200a4.png)

edit: Nope.. the css ref didn't help

**Comment by charlespockert** [comment]
Ah this one I know the answer to, install system js CSS plugin as so

`jspm install css=github:system js/plugin-css`

**Comment by charlespockert** [comment]
@eaidland Ah this one I know the answer to, install system js CSS plugin as so

`jspm install css=github:systemjs/plugin-css`

**Comment by eaidland** [comment]
But it's already there from earlier...
"css": "github:systemjs/plugin-css@0.1.17",

And now 
"systemjs/plugin-css": "github:systemjs/plugin-css@0.1.17",

Well it worked... but what's the standard?

**Comment by charlespockert** [comment]
It should be installed as `css` - when you import stuff it uses the file extension as the name of the plugin - I'm not sure what it's supposed to be as standard...

I assume `css` as otherwise I can't see how systemJS is going to know what to load unless you write `import 'some-css-file.css!systemjs/plugin-css'`?

**Comment by charlespockert** [comment]
@eaidland so I take it it's actually working now?!

**Comment by eaidland** [comment]
Ok... so do you need to update something so that we could use the standard "css": "github:systemjs/plugin-css@0.1.17" instead of "systemjs/plugin-css": "github:systemjs/plugin-css@0.1.17".... I don't know what's the standard.

It's working :+1:  Woohoo :boom:

**Comment by charlespockert** [comment]
Nice, thanks for all the help resolving it :)

Hopefully deploys will go a bit smoother from now on!

**Comment by johntom** [comment]
If possible could @eaidland email me zip (or 7zip) copy of working directory so I can do a compare and see why my win10 version  doesn't work. jrt@gtz.com.
thanks,
John

**Comment by anuradhabathina** [comment]
Hi Charlespockert
This solution worked for me. Thank you so much
I want to implement sorting colums along with filtering. do we need to install any other plugin for this

**Comment by anuradhabathina** [comment]
how to bind sorting to the columns?

**Comment by anuradhabathina** [comment]
Can any one help to add sorting to the columns in Charlespockert grid
