### ISSUE TITLE
Does not work in IE or Firefox

### ISSUE THREAD

**Issue by BringerOD** [CharlesPockert/aurelia-bs-grid#65]
I am having a similar issue working with Aurelia and it not working in the other browsers,  and I knew the grid would be having the same issues.  I checked and it does not work.

I have a repo if my issues as well.

https://github.com/BringerOD/skeleton-navigation
Just go to the test1 tab and it does not work in IE and Firefox.

Is it a known issues that Aurelia does not work with Firefox or the latest IE?

**Comment by charlespockert** [comment]
Yes it was an issue that's been fixed in the latest framework release. I've updated the master branch with the changes required to support the new release so if you grab that version you should be good to go!

**Comment by BringerOD** [comment]
Thanks I will check it out.

**Comment by BringerOD** [comment]
Ok,  my repo is updated and synced with the latest and it is now not working in any browser.

https://github.com/BringerOD/skeleton-navigation

Go to the test1 navigation link.  It is suppose to open and close a row.  
- Chrome works the first time it opens.  Then the rows expand without error but are still hidden.
- IE, Firefox, Edge, all just don't work.  They don't expand.

Please check it out.
