### ISSUE TITLE
How to remove specific elements from grid footer

### ISSUE THREAD

**Issue by UmaBharathiK** [CharlesPockert/aurelia-bs-grid#77]
How can I remove specific elements like PageSizeBox or Paging Summary from the grid footer? 
I tried using showPageSizeBox = "false" and showPageSizeBox.bind = "false" in my html page inside the grid tag but it doesn't seem to work.

**Comment by charlespockert** [comment]
You have to `kebab-case` the property names in Aurelia since the DOM is case insensitive

Try `show-page-size-box.bind="false"`

**Comment by UmaBharathiK** [comment]
It worked! thank you
