### ISSUE TITLE
Up/down arrow images not resolving

### ISSUE THREAD

**Issue by charlespockert** [CharlesPockert/aurelia-bs-grid#8]
Wrong paths used - need to work out how to do this - anyone know?!

Could use SVG instead...

**Comment by charlespockert** [comment]
From @delebash on gitter:

@CharlesPockert Not sure if this will help but maybe add something to your paths directory like "src/": "dist/", that worked for me when I wanted to load a resource that wasn't in jspm config but still loaded via a module like a css file
there is a "*" after src/ and dist/

Will have a try of this

**Comment by charlespockert** [comment]
Seems to have fixed itself :)

**Comment by charlespockert** [comment]
Didn't - turns out I had the images in my demo project in the folder it was expecting (but not the plugin one) doh!

**Comment by delebash** [comment]
See if adding  "src/_": "dist/_", to your paths in config.js, or whatever your path is.  For me adding the above works when I try to import a css file that is not loaded via jspm. eg, in my app.ts I import my styles via import 'src/css/styles.css!';  If I do not have the src/\* added to my paths config then I get 404 http://localhost:9000/dist/src/css/styles.css
